// 融合版(standard,主力):运维/SRE 校招标尺。字段一律中文。
import { ProfessionPreset } from '../../common/types';

export const devopsSreCampus: ProfessionPreset = {
  id: "devops-sre-campus",
  profession: "运维/SRE",
  stage: 'campus',
  tier: 'standard',
  displayName: "运维/SRE · 校招(融合版)",
  dimensions: [
    { key: "linux_network_internals", name: "Linux系统底层与网络原理", weight: 25,
      whatGoodLooksLike: "不是会敲命令而是懂原理:能讲清进程/线程与内存管理、IO多路复用、TCP三次握手四次挥手为何如此、DNS解析全链路、OOM如何定位;能说出在什么场景下用top/netstat/strace/tcpdump定位到哪一层。搭过生产级Nginx/MySQL/Redis并写得出调参细节和踩过的坑。",
      campusEvidence: "生产或自建环境的故障排查记录(用什么工具→定位到哪一层→怎么修);自建服务的调参与踩坑笔记;RHCE证书;计算机网络/操作系统课程能在追问时讲清原理而非背命令;Homelab/技术博客记录排障过程。",
      commonGaps: "技能栏堆Linux/网络词汇却答不出TCP握手为何不是两次、问DNS解析链路就卡壳;只会敲命令不懂背后机制【反模式·命令背诵工:背得出top却讲不出它读的是哪个内核指标】。" },
    { key: "container_kubernetes", name: "容器化与K8s实操能力", weight: 25,
      whatGoodLooksLike: "在自建集群或公有云学生版上独立部署过完整应用,能讲清Pod生命周期、调度原理、CNI网络、HPA配置,以及遇到调度/网络问题时如何排查;K8s/Docker是亲手跑过而非课件里见过。",
      campusEvidence: "CKA证书(上机实操,含金量最高);个人项目在华为云/阿里云学生版或自建集群部署应用并附调度/网络排障描述;实习参与K8s集群运维、Pod故障排查、HPA配置;GitHub有可复现的部署清单或文档。",
      commonGaps: "只写「熟悉K8s」「了解Docker」却零实操描述,等同于没写;面试一问Pod生命周期、CNI插件区别就答不上【反模式·熟悉党:简历全是「熟悉/了解」,一追问全空】。" },
    { key: "stability_engineering", name: "故障排查与稳定性工程思维", weight: 22,
      whatGoodLooksLike: "简历不只写「部署了什么」而有真实排障与稳定性经历:参与过故障复盘并能说清root cause分析方法(5Why/鱼骨图),设计过限流/熔断/降级方案(哪怕课程项目),理解SLI/SLO与容量评估。这是区分「会排查的工程师」和「只会装环境的操作员」的核心。",
      campusEvidence: "实习中的故障复盘经历(能描述根因定位过程);项目里的限流熔断降级设计;云原生/SRE方向竞赛或CNCF社区参与(提过Issue/PR);MTTD/MTTR等指标的量化结果。",
      commonGaps: "简历只见「部署了XX服务」却无任何故障处理与稳定性环节,SRE核心价值在排查而非装环境;写「优化了监控效果很好」却无任何MTTD/MTTR/SLO数字【反模式·只装不修工:简历全是部署清单,零故障定位,稳定性贡献为零】。" },
    { key: "observability_monitoring", name: "可观测性与监控告警体系", weight: 16,
      whatGoodLooksLike: "搭过Prometheus+Grafana+Alertmanager全链路,说得清覆盖了哪些指标类型和告警规则的设计思路;懂Metrics/Logs/Traces三支柱(ELK/Loki日志聚合、Jaeger/SkyWalking链路追踪);考察的是监控思维而非单个工具会不会装。",
      campusEvidence: "项目搭建Prometheus+Grafana+Alertmanager并写出指标覆盖与告警规则设计;实习参与告警治理(降噪/分级)并说清MTTD降低多少;日志聚合或链路追踪的实操经历;GitHub有监控配置仓库。",
      commonGaps: "技能栏列了Prometheus/ELK/Grafana却没有任何指标选型或告警设计的上下文;监控只到「装好能出图」、不涉及降噪分级与告警治理思路【反模式·仪表盘截图侠:晒得出Grafana大盘,讲不出为什么监这几个指标】。" },
    { key: "automation_coding", name: "自动化编程能力(Python/Shell/Go)", weight: 12,
      whatGoodLooksLike: "用Shell+Python(Go加分)写过真正跑在生产或个人服务器上的运维工具——自动巡检脚本、告警推送Bot、发布流水线、CMDB/作业调度——有GitHub链接或代码片段,并有实际效果数据。这是区分「运维操作工」和「SRE工程师」的分水岭。",
      campusEvidence: "GitHub上的运维工具/脚本仓库(有Star更好);实习参与平台研发(CMDB/变更平台/作业调度);项目里自动化工具的量化效果(把N小时手工巡检降到分钟级);配置过GitLab CI/GitHub Actions+ArgoCD或Terraform/Ansible的IaC实操。",
      commonGaps: "只写「会写Python脚本」却没有任何仓库或上线效果,看不出脚本解决了什么重复劳动;纯手工运维、零自动化沉淀【反模式·手动运维工:重复操作不写代码沉淀,典型操作员而非工程师】。" },
  ],
  explanationRubric: "每个维度必须给出 why:① 指出简历中具体命中/缺失的事实(原理讲解深度、实操描述、故障排查闭环、监控设计思路、自动化工具仓库/效果、实习公司、CKA/RHCE证书、云原生竞赛/CNCF参与),写进 evidenceFound/gap;② 说明在校招运维/SRE语境下为何重要(例如该岗位本质是在应届生中找有工程师思维的初级系统工程师,核心标尺是能否在生产故障中独立定位根因、有无数据佐证的实操、能否写代码自动化解决重复问题);③ 命中反模式直接点名(如「命令背诵工」「熟悉党」「只装不修工」「仪表盘截图侠」「手动运维工」),不得空泛。分数必须与 why 一致:满纸「熟悉/了解」且零实操、零排障、零数字的简历不得给中高分。",
  rewriteGuidance: "改写只能基于简历已有内容重组、量化、补技术证据链,把模糊运维表述讲精准:讲清用了什么技术、解决什么问题、量级多大。例如把「参与了监控系统建设」改写为「基于简历已写的Prometheus+Grafana搭建,覆盖的指标类型与告警规则」这类更精准的表述(仅当原句已体现该工作时);把「部署了K8s集群」补上原文已有的规模/节点数/排障细节;用精准动词(定位/复盘/调参/降噪)与可量化指标(MTTD/MTTR/SLO/巡检耗时)增强可信度。严禁替候选人添加原句没有体现的能力或技术名词——简历没写过CKA、没写过故障复盘、没写过Go,就一律走「建议补充(gap_advice)」而非编造;严禁把「协助/参与」夸大为「独立/主导」;缺数字处用 [具体数字] 占位并在 reason 说明「建议补充真实数据」;original 必须是简历原文一字不差。",
  resumeConventions: "中国校招运维/SRE惯例核查:① 学历硬规则——互联网大厂SRE实际筛选线多为本科,头部(字节/阿里/腾讯)非985/211需有显著补偿项(云原生竞赛奖/知名开源贡献/大厂实习);计算机/网络工程/软件工程为核心专业,非科班需格外强调自学路径与实操项目;硬件/网络运维岗学历相对宽松但SRE普遍更严。② 证书优先级——CKA(上机实操,含金量最高)> RHCE(Linux深度,传统运维加分)> 华为HCIE-openEuler/HCIE-Cloud(华为系/国企央企权重高)> 阿里云ACA/ACP > AWS/GCP(外企有效,国内大厂优先级较低);CKA一个上机证胜过三个笔试认证。③ 格式——应届一页为主、最多两页;技能栏严禁词云堆砌,每个技术点必须有后续项目/实习佐证;项目用「背景→我的角色→技术选型→数字结果」结构,不要叙事散文;不写个人评价/爱好等软性段落。④ 反信号——出现「精通」但面试无法支撑;只写部署不写排查;前后端开发项目硬包装成「云原生项目」(基础设施层一追问就露馅);培训班套路暴露(「系统学习了Linux/K8s」+知名机构证明)在大厂直接降权;过多运营/产品类实习、零技术实操背景。",
};
